### ISSUE TITLE
段错误 (核心已转储)

### ISSUE THREAD

**Issue by Liu-xiaoyu11** [boqian-li/GarmentDreamer#1]
Hello, @boqian-li ：
Your excellent work has given me a great deal of inspiration, and I thank you very much. I have encountered some issues while trying to reproduce the code. Do you have any good suggestions? Regarding whether the prompt in the command-line statement should be enclosed in double quotes: I ran the following commands:
CUDA_VISIBLE_DEVICES=1 python launch_garmentdreamer.py --template_path /mnt/sda2/code/GarmentDreamer-main/input_data/ori_meshes/a_American_Western_cowboy_style_jumpsuit_made_of_brown_leather/Jumpsuit_747_translated.obj --prompt a blue denim tee；
CUDA_VISIBLE_DEVICES=1 python launch_garmentdreamer.py --template_path /mnt/sda2/code/GarmentDreamer-main/input_data/ori_meshes/a_American_Western_cowboy_style_jumpsuit_made_of_brown_leather/Jumpsuit_747_translated.obj --prompt "a blue denim tee"；
CUDA_VISIBLE_DEVICES=1 python launch_garmentdreamer.py --template_path /mnt/sda2/code/GarmentDreamer-main/input_data/ori_meshes/a_American_Western_cowboy_style_jumpsuit_made_of_brown_leather/Jumpsuit_747_translated.obj --prompt "blue denim tee"；
All of them resulted in the following issue: 
![image](https://github.com/user-attachments/assets/3777d3bd-a3a2-481a-af6d-0c5357924042)
I suspect that my prompt settings might be incorrect, but I have tried several variations without success. Do you have any suggestions? I appreciate your help.
I look forward to your reply.

**Comment by boqian-li** [comment]
Hi @Liu-xiaoyu11 , thanks for your interest in our work. 
It looks like there's a problem with Pytorch Cuda and xformers. Could you please check first with the command `python -c "import torch; print(torch.cuda.is_available())"`? 

And it looks like you are using the xformers which requires cuda==12.1, please also make sure the cuda version for pytorch is aligned with that with the command `python -c "import torch; print(torch.version.cuda)"`

IF there are any other questions, please let me know.

**Comment by Liu-xiaoyu11** [comment]
> Hi @Liu-xiaoyu11 , thanks for your interest in our work. It looks like there's a problem with Pytorch Cuda and xformers. Could you please check first with the command `python -c "import torch; print(torch.cuda.is_available())"`?
> 
> And it looks like you are using the xformers which requires cuda==12.1, please also make sure the cuda version for pytorch is aligned with that with the command `python -c "import torch; print(torch.version.cuda)"`
> 
> IF there are any other questions, please let me know.
Hello, @boqian-li :
I just used the following command to try setting CUDA to 12.1,conda install pytorch==2.3.1 torchvision==0.18.1 torchaudio==2.3.1 pytorch-cuda=12.1 -c pytorch -c nvidia. However, this causes issues when I attempt to install diff-gaussian-rasterization. 
![image](https://github.com/user-attachments/assets/c82b303f-9421-4d0e-8471-0045fdf7ac67)
Do you have any suggestions on how to resolve this? I look forward to your reply.

**Comment by boqian-li** [comment]
hi, actually you don't need to follow the version of cuda that xformers needs, it actually depends on the version of xformers you installed. 

Just install cuda runtime with verision==11.8, and make sure it's selected with the command: nvcc --version.  Then follow the environment setup instructions in readme.md. 

pytorch has its cuda toolkit version (exactly the version in your installation command: like cu113 cu118, etc.) 
and on your GPU, you all so have different cuda runtime compiler versions (it seems you have CUDA==11.3, you can try to run `nvcc --version` to find it out)

although it usually works when the two versions are different, I recommend installing the same pytorch-cuda version as the Nvidia cuda compiler version.

**Comment by Liu-xiaoyu11** [comment]
> hi, try this: [vllm-project/vllm#1453](https://github.com/vllm-project/vllm/issues/1453)
Hello, @boqian-li 
If I match CUDA 11.3 using the following command:pip install torch==1.12.1+cu113 torchvision==0.13.1+cu113 torchaudio==0.12.1 --extra-index-url https://download.pytorch.org/whl/cu113
Will this affect the subsequent running of my code? Thank you very much for your help. I look forward to your reply.

**Comment by boqian-li** [comment]
I recommend just deleting the virtual env first. 
check the cuda runtime version with command `nvcc --version` and make sure you are using the version==11.8 (seems you are using 11.3 at the moment)
then follow the setup instructions (pytorch-cuda==11.8 especially) to rebuild the virtual environment from scratch then it should work. 
Any other questions, let me know please, glad to help!

**Comment by Liu-xiaoyu11** [comment]
> I recommend just deleting the virtual env first. check the cuda runtime version with command `nvcc --version` and make sure you are using the version==11.8 (seems you are using 11.3 at the moment) then follow the setup instructions (pytorch-cuda==11.8 especially) to rebuild the virtual environment from scratch then it should work. Any other questions, let me know please, glad to help!

Hello, @boqian-li:
Thank you very much for your patient responses. The issues mentioned above have been resolved; it was due to incorrect installation commands for xformers, which messed up the environment. Your assistance has been very helpful to me. I have two more small questions:
What software did you use to view the final reconstructed .obj file? When I tried viewing it directly in Blender, the texture information did not display.
Regarding the items you mentioned on GitHub, will there be further uploads?
![image](https://github.com/user-attachments/assets/49580f55-3e4f-46c8-955d-d708bb780b6d)
Once again, thank you very much for your help. I look forward to your reply.

**Comment by boqian-li** [comment]
Hi @Liu-xiaoyu11  glad to hear that!
I use MeshLab for visualization and Blender should also work if you enable the texture option correctly. 
Yeah they are planned :)

**Comment by Liu-xiaoyu11** [comment]
> Hi @Liu-xiaoyu11 glad to hear that! I use MeshLab for visualization and Blender should also work if you enable the texture option correctly. Yeah they are planned :)

Hi, @boqian-li 
I'm very happy that the issue is now resolved and everything opens correctly. I look forward to you uploading the remaining code soon so I can learn from your excellent work. Thank you again for your patient responses. I will close this conversation now, and if I have any further questions in the future, I will leave you a message.

**Comment by boqian-li** [comment]
@Liu-xiaoyu11 great ;)
