### ISSUE TITLE
How to fit generated clothing onto any human model?

### ISSUE THREAD

**Issue by jingfengguo-ai** [boqian-li/GarmentDreamer#2]
Thank you very much for your outstanding work! I would like to ask if this project supports fitting the generated clothing onto any human model？like the video demo you showcased

**Comment by boqian-li** [comment]
Hi @gjgjgjfff , thanks for your interest in the work.  Actually, you can generate a garment, put it on a human model, and simulate it using software like Blender, Unity, Houdini, etc. I suppose it's also possible that you obtain a simulated garment mesh which is already on a human model, generate a garment mesh using GarmentDreamer, and then put it back.
