### ISSUE TITLE
Poor result in my own Mesh template

### ISSUE THREAD

**Issue by jingfengguo-ai** [boqian-li/GarmentDreamer#3]
When I use my own Mesh template, the results are poor. Could you please let me know how to align my Mesh template with the provided template in terms of direction?
The output of "gs_check" is as shown in the figure below.
![image](https://github.com/user-attachments/assets/537711a8-7452-428a-b391-7ebbc1c8a11e)

**Comment by boqian-li** [comment]
Hi @gjgjgjfff, it seems the camera is too close to the garment. 
You can download the example garment meshes with the link on README and align your own mesh to them within the same range manually.

**Comment by boqian-li** [comment]
You can download the example garment meshes using the link in the README and align your own mesh to them manually within the same range.
